# Generated by Django 4.1.5 on 2023-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiario', '0004_alter_noticia_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img1',
            field=models.ImageField(null=True, upload_to='noticaiIMG'),
        ),
    ]
