# Generated by Django 4.1.5 on 2023-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiario', '0007_alter_noticia_img4_alter_noticia_img5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img1',
            field=models.ImageField(null=True, upload_to='noticiaIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='noticiaIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='noticiaIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='noticiaIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='noticiaIMG'),
        ),
    ]
