# Generated by Django 4.1.5 on 2023-02-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LineaDeMetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.IntegerField(default=0)),
                ('distancia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='fecha incidencia')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacion', to='incidencias.estaciones')),
            ],
        ),
        migrations.AddField(
            model_name='estaciones',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeroLinea', to='incidencias.lineademetro'),
        ),
    ]
