# Generated by Django 4.1.5 on 2023-02-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('img1', models.ImageField(null=True, upload_to='equipos')),
                ('img2', models.ImageField(null=True, upload_to='equipos')),
                ('img3', models.ImageField(null=True, upload_to='equipos')),
                ('img4', models.ImageField(null=True, upload_to='equipos')),
                ('img5', models.ImageField(null=True, upload_to='equipos')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
