# Generated by Django 4.1.5 on 2023-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiario', '0002_rename_equipo_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img1',
            field=models.ImageField(null=True, upload_to='noticaiIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img2',
            field=models.ImageField(null=True, upload_to='noticaiIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img3',
            field=models.ImageField(null=True, upload_to='noticaiIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img4',
            field=models.ImageField(null=True, upload_to='noticaiIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img5',
            field=models.ImageField(null=True, upload_to='noticaiIMG'),
        ),
    ]
