# Generated by Django 4.1.5 on 2023-02-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiario', '0003_alter_noticia_img1_alter_noticia_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='noticaiIMG'),
        ),
    ]
