# Generated by Django 4.1.5 on 2023-02-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiario', '0005_alter_noticia_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='noticaiIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='noticaiIMG'),
        ),
    ]
