# Generated by Django 4.1.5 on 2023-02-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiario', '0006_alter_noticia_img2_alter_noticia_img3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='noticaiIMG'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='noticaiIMG'),
        ),
    ]
